//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TAAPs.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bank
    {
        public Bank()
        {
            this.ITaxpayerBanks = new HashSet<ITaxpayerBank>();
            this.CBanks = new HashSet<CBank>();
        }
    
        public string BankCode { get; set; }
        public string BankName { get; set; }
    
        public virtual ICollection<ITaxpayerBank> ITaxpayerBanks { get; set; }
        public virtual ICollection<CBank> CBanks { get; set; }
    }
}
