//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TAAPs.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class BusinessLine
    {
        public BusinessLine()
        {
            this.TaxAgents2 = new HashSet<CorporateTaxpayer>();
            this.ITaxpayers = new HashSet<ITaxpayer>();
            this.CTINRequests = new HashSet<CTINRequest>();
            this.ITINRequests = new HashSet<ITINRequest>();
        }
    
        public string BusinessLineId { get; set; }
        public string GroupId { get; set; }
        public string BusinessLineName { get; set; }
    
        public virtual BusinessLineGroup BusinessLineGroup { get; set; }
        public virtual ICollection<CorporateTaxpayer> TaxAgents2 { get; set; }
        public virtual ICollection<ITaxpayer> ITaxpayers { get; set; }
        public virtual ICollection<CTINRequest> CTINRequests { get; set; }
        public virtual ICollection<ITINRequest> ITINRequests { get; set; }
    }
}
