//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TAAPs.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CollectionAgent
    {
        public string AgentId { get; set; }
        public string AgentName { get; set; }
        public string AgentType { get; set; }
        public string DistributorType { get; set; }
        public string Description { get; set; }
        public string MobileNo { get; set; }
        public string SecurityCode { get; set; }
        public string MarketingCode { get; set; }
        public string Email { get; set; }
        public string Country { get; set; }
        public string Status { get; set; }
        public string ContactName { get; set; }
        public string ContactEmail { get; set; }
        public string ContactPhone { get; set; }
        public string ContactAddress1 { get; set; }
        public string ContactAddress2 { get; set; }
        public string ContactAddress3 { get; set; }
        public string ContactAddress4 { get; set; }
    }
}
