//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TAAPs.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CorporateBranch
    {
        public CorporateBranch()
        {
            this.CTransfers = new HashSet<CorporateTransfer>();
        }
    
        public string BranchTIN { get; set; }
        public string NewTIN { get; set; }
        public string OldTIN { get; set; }
        public string CorporateTIN { get; set; }
        public string BranchName { get; set; }
        public string TaxOfficeId { get; set; }
        public string OfficeStatus { get; set; }
        public string StreetNo { get; set; }
        public string Street { get; set; }
        public string City { get; set; }
        public string LGA { get; set; }
        public string State { get; set; }
        public string Email { get; set; }
        public string Phone1 { get; set; }
        public string Phone2 { get; set; }
        public string Phone3 { get; set; }
        public string MailingAddress { get; set; }
        public string OldVATNumber { get; set; }
        public Nullable<System.DateTime> RegDate { get; set; }
        public Nullable<bool> Status { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public bool EmailNotified { get; set; }
    
        public virtual CorporateTaxpayer CorporateTaxpayer { get; set; }
        public virtual TaxOffice TaxOffice { get; set; }
        public virtual ICollection<CorporateTransfer> CTransfers { get; set; }
        public virtual User User { get; set; }
    }
}
