//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TAAPs.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CorporateTaxpayer
    {
        public CorporateTaxpayer()
        {
            this.Branches = new HashSet<CorporateBranch>();
            this.CAssociates = new HashSet<CAssociate>();
            this.CBanks = new HashSet<CBank>();
            this.CDirectors = new HashSet<CDirector>();
            this.CRepresentatives = new HashSet<CRepresentative>();
            this.CShareHolders = new HashSet<CShareHolder>();
            this.CTurnovers = new HashSet<CTurnover>();
            this.CTaxpayerFiles = new HashSet<CTaxpayerFile>();
        }
    
        public string TIN { get; set; }
        public string NewTIN { get; set; }
        public string RCNo { get; set; }
        public string OldTIN { get; set; }
        public string CompanyName { get; set; }
        public System.DateTime DateOfIncorporation { get; set; }
        public Nullable<System.DateTime> DateOfCommencement { get; set; }
        public string FinancialYearBegin { get; set; }
        public string FinancialYearEnd { get; set; }
        public string BusLine { get; set; }
        public Nullable<System.DateTime> RegDate { get; set; }
        public string RegAddStreetNo { get; set; }
        public string RegAddStreet { get; set; }
        public string RegAddCity { get; set; }
        public string RegAddState { get; set; }
        public string RegAddLGA { get; set; }
        public string Phone1 { get; set; }
        public string Phone2 { get; set; }
        public string Phone3 { get; set; }
        public Nullable<bool> IsNewBusiness { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string CreatedBy { get; set; }
        public string CompanyType { get; set; }
        public long SNo { get; set; }
        public string RecordSource { get; set; }
        public string TaxAuthority { get; set; }
    
        public virtual BusinessLine BusinessLine { get; set; }
        public virtual ICollection<CorporateBranch> Branches { get; set; }
        public virtual User User { get; set; }
        public virtual ICollection<CAssociate> CAssociates { get; set; }
        public virtual ICollection<CBank> CBanks { get; set; }
        public virtual ICollection<CDirector> CDirectors { get; set; }
        public virtual ICollection<CRepresentative> CRepresentatives { get; set; }
        public virtual ICollection<CShareHolder> CShareHolders { get; set; }
        public virtual ICollection<CTurnover> CTurnovers { get; set; }
        public virtual ICollection<CTaxpayerFile> CTaxpayerFiles { get; set; }
    }
}
