//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TAAPs.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CShareHolder
    {
        public string TIN { get; set; }
        public string ShareHolderName { get; set; }
        public string ShareHolderAddress { get; set; }
        public Nullable<int> ShareVolume { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
    
        public virtual CorporateTaxpayer TaxAgents2 { get; set; }
        public virtual User User { get; set; }
    }
}
