//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TAAPs.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CTINRequest
    {
        public long RequestId { get; set; }
        public string CacNumber { get; set; }
        public string BNNumber { get; set; }
        public int CompanyTypeId { get; set; }
        public string PreviousFCTTin { get; set; }
        public string CompanyName { get; set; }
        public string BusinessLineId { get; set; }
        public string TaxOfficeId { get; set; }
        public System.DateTime RegistrationDate { get; set; }
        public Nullable<System.DateTime> CommencementDate { get; set; }
        public string RegisteredAddressStreetNo { get; set; }
        public string RegisteredAddressStreet { get; set; }
        public string RegisteredAddressCity { get; set; }
        public int RegisteredAddressCountryId { get; set; }
        public string RegisteredAddressStateId { get; set; }
        public int RegisteredAddressLgaId { get; set; }
        public string PrimaryPhone { get; set; }
        public string SecondaryPhone { get; set; }
        public string Email { get; set; }
        public string Website { get; set; }
        public string ContactPerson { get; set; }
        public string ContactPersonPhone { get; set; }
        public string Status { get; set; }
        public string RecordSource { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreateDate { get; set; }
    
        public virtual BusinessLine BusinessLine { get; set; }
        public virtual Country Country { get; set; }
        public virtual LGA LGA { get; set; }
        public virtual RegisteredCompany RegisteredCompany { get; set; }
        public virtual State State { get; set; }
        public virtual User User { get; set; }
        public virtual CompanyType CompanyType { get; set; }
        public virtual TaxOffice TaxOffice { get; set; }
    }
}
