//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TAAPs.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CTINRequest
    {
        public int RequestId { get; set; }
        public string RCNo { get; set; }
        public string CompanyName { get; set; }
        public string CompanyType { get; set; }
        public string BusinessLineId { get; set; }
        public string TaxOfficeId { get; set; }
        public System.DateTime DateOfIncorporation { get; set; }
        public Nullable<System.DateTime> DateOfCommencement { get; set; }
        public string FinancialYearBegin { get; set; }
        public string FinancialYearEnd { get; set; }
        public string BusinessStreetNo { get; set; }
        public string BusinessStreet { get; set; }
        public string BusinessCity { get; set; }
        public string BusinessStateId { get; set; }
        public Nullable<int> BusinessLgaId { get; set; }
        public string Phone1 { get; set; }
        public string Phone2 { get; set; }
        public string Phone3 { get; set; }
        public string Email { get; set; }
        public System.DateTime CreateDate { get; set; }
    
        public virtual BusinessLine BusinessLine { get; set; }
        public virtual LGA LGA { get; set; }
        public virtual State State { get; set; }
        public virtual TaxOffice TaxOffice { get; set; }
    }
}
