//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TAAPs.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CTurnover
    {
        public string TIN { get; set; }
        public System.DateTime YearEnd { get; set; }
        public Nullable<decimal> Sales { get; set; }
        public Nullable<decimal> NetIncome { get; set; }
        public string TurnOverType { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
    
        public virtual User User { get; set; }
    }
}
