//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TAAPs.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class GeneratedReceipt
    {
        public string ReceiptId { get; set; }
        public string UserName { get; set; }
        public System.DateTime CreateDate { get; set; }
    
        public virtual User User { get; set; }
    }
}
