//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TAAPs.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class IAssessmentIncome
    {
        public int AssessmentId { get; set; }
        public int IncomeId { get; set; }
        public decimal Amount { get; set; }
    
        public virtual TaxIncome TaxIncome { get; set; }
        public virtual IAssessment IAssessment { get; set; }
    }
}
