//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TAAPs.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class IAssessment
    {
        public IAssessment()
        {
            this.IAssessmentExclusions = new HashSet<IAssessmentExclusion>();
            this.IAssessmentIncomes = new HashSet<IAssessmentIncome>();
            this.IAssessmentFiles = new HashSet<IAssessmentFile>();
            this.IPenalties = new HashSet<IPenalty>();
        }
    
        public int AssessmentId { get; set; }
        public int TaxAccountNo { get; set; }
        public System.DateTime AssessmentDate { get; set; }
        public int AssessmentYear { get; set; }
        public string FormNo { get; set; }
        public string FormTitle { get; set; }
        public Nullable<decimal> GrossIncome { get; set; }
        public Nullable<decimal> ExemptAmount { get; set; }
        public Nullable<decimal> AssessableIncome { get; set; }
        public Nullable<decimal> TaxPayable { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreateDate { get; set; }
    
        public virtual ICollection<IAssessmentExclusion> IAssessmentExclusions { get; set; }
        public virtual ICollection<IAssessmentIncome> IAssessmentIncomes { get; set; }
        public virtual ITaxAccount ITaxAccount { get; set; }
        public virtual User User { get; set; }
        public virtual ICollection<IAssessmentFile> IAssessmentFiles { get; set; }
        public virtual ICollection<IPenalty> IPenalties { get; set; }
    }
}
