//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TAAPs.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class IInterest
    {
        public int InterestId { get; set; }
        public int TaxAccountNo { get; set; }
        public string Description { get; set; }
        public Nullable<int> InterestRate { get; set; }
        public decimal InterestAmount { get; set; }
        public decimal ComputedBalance { get; set; }
        public System.DateTime CreateDate { get; set; }
    
        public virtual ITaxAccount ITaxAccount { get; set; }
    }
}
