//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TAAPs.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class IPenalty
    {
        public int PenaltyId { get; set; }
        public int AssessmentId { get; set; }
        public string Description { get; set; }
        public Nullable<int> Rate { get; set; }
        public string PenaltyType { get; set; }
        public decimal PenaltyAmount { get; set; }
        public decimal TaxPayable { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string CreatedBy { get; set; }
    
        public virtual IAssessment IAssessment { get; set; }
        public virtual User User { get; set; }
    }
}
