//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TAAPs.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ITaxpayerAddress
    {
        public long AddressId { get; set; }
        public string TIN { get; set; }
        public string StreetNo { get; set; }
        public string AddressLine1 { get; set; }
        public string AddressLine2 { get; set; }
        public string City { get; set; }
        public string StateId { get; set; }
        public Nullable<int> LgaId { get; set; }
        public Nullable<int> CountryId { get; set; }
        public string PostCode { get; set; }
        public bool IsPrimary { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string CreatedBy { get; set; }
    
        public virtual ITaxpayer ITaxpayer { get; set; }
        public virtual LGA LGA { get; set; }
        public virtual State State { get; set; }
        public virtual User User { get; set; }
    }
}
