//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TAAPs.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ITaxpayerBank
    {
        public string TIN { get; set; }
        public string BankCode { get; set; }
        public string AccountNumber { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreateDate { get; set; }
    
        public virtual ITaxpayer ITaxpayer { get; set; }
        public virtual Bank Bank { get; set; }
    }
}
