//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TAAPs.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ITaxAccount
    {
        public ITaxAccount()
        {
            this.IAssessments = new HashSet<IAssessment>();
            this.IInterests = new HashSet<IInterest>();
        }
    
        public int TaxAccountNo { get; set; }
        public string TIN { get; set; }
        public string TaxTypeId { get; set; }
        public string Currency { get; set; }
        public string Description { get; set; }
        public string Status { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreateDate { get; set; }
    
        public virtual ITaxpayer ITaxpayer { get; set; }
        public virtual ICollection<IAssessment> IAssessments { get; set; }
        public virtual TaxType TaxType { get; set; }
        public virtual ICollection<IInterest> IInterests { get; set; }
    }
}
