//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TAAPs.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ITaxpayer
    {
        public ITaxpayer()
        {
            this.ITaxpayerBanks = new HashSet<ITaxpayerBank>();
            this.ITaxpayerAssociates = new HashSet<ITaxpayerAssociate>();
            this.ITaxpayerOtherIncomes = new HashSet<ITaxpayerOtherIncome>();
            this.ITaxpayerRepresentatives = new HashSet<ITaxpayerRepresentative>();
            this.ITaxpayerTransfers = new HashSet<ITaxpayerTransfer>();
            this.ITaxAccounts = new HashSet<ITaxAccount>();
            this.ITaxpayerFiles = new HashSet<ITaxpayerFile>();
        }
    
        public int SNo { get; set; }
        public string TIN { get; set; }
        public string NewTIN { get; set; }
        public string RegNo { get; set; }
        public Nullable<System.DateTime> RegDate { get; set; }
        public string TaxpayerName { get; set; }
        public string BusAddNo { get; set; }
        public string BusAddStreet { get; set; }
        public string BusAddCity { get; set; }
        public string BusAddLGA { get; set; }
        public string BusAddState { get; set; }
        public string MailingAddress { get; set; }
        public string Email { get; set; }
        public string Phone1 { get; set; }
        public string Phone2 { get; set; }
        public string Phone3 { get; set; }
        public string EmpAddNo { get; set; }
        public string EmpAddStreet { get; set; }
        public string EmpAddCity { get; set; }
        public string EmpAddLGA { get; set; }
        public string EmpAddState { get; set; }
        public string BusLine { get; set; }
        public Nullable<System.DateTime> DateOfCommencement { get; set; }
        public string AcctYearEnd { get; set; }
        public string TaxAuthority { get; set; }
        public string TaxOfficeID { get; set; }
        public string OldTIN { get; set; }
        public string RecordSource { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string EmploymentType { get; set; }
        public Nullable<int> BVN { get; set; }
        public Nullable<bool> EmailNotified { get; set; }
    
        public virtual ICollection<ITaxpayerBank> ITaxpayerBanks { get; set; }
        public virtual ICollection<ITaxpayerAssociate> ITaxpayerAssociates { get; set; }
        public virtual ICollection<ITaxpayerOtherIncome> ITaxpayerOtherIncomes { get; set; }
        public virtual ICollection<ITaxpayerRepresentative> ITaxpayerRepresentatives { get; set; }
        public virtual BusinessLine BusinessLine { get; set; }
        public virtual ICollection<ITaxpayerTransfer> ITaxpayerTransfers { get; set; }
        public virtual TaxOffice TaxOffice { get; set; }
        public virtual ICollection<ITaxAccount> ITaxAccounts { get; set; }
        public virtual ICollection<ITaxpayerFile> ITaxpayerFiles { get; set; }
    }
}
