//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TAAPs.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ITINRequest
    {
        public int RequestId { get; set; }
        public string TaxpayerName { get; set; }
        public string RegistrationNo { get; set; }
        public Nullable<System.DateTime> RegistrationDate { get; set; }
        public string TaxOfficeId { get; set; }
        public string StreetNo { get; set; }
        public string Street { get; set; }
        public string City { get; set; }
        public Nullable<int> LgaId { get; set; }
        public string StateId { get; set; }
        public string Email { get; set; }
        public string Phone1 { get; set; }
        public bool InEmployment { get; set; }
        public string EmploymentType { get; set; }
        public string BusinessLineId { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string Phone2 { get; set; }
    
        public virtual BusinessLine BusinessLine { get; set; }
        public virtual LGA LGA { get; set; }
        public virtual State State { get; set; }
        public virtual TaxOffice TaxOffice { get; set; }
    }
}
