//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TAAPs.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class LGA
    {
        public LGA()
        {
            this.TaxOffices = new HashSet<TaxOffice>();
            this.CTINRequests = new HashSet<CTINRequest>();
            this.ITINRequests = new HashSet<ITINRequest>();
        }
    
        public int LGAId { get; set; }
        public string LGAName { get; set; }
        public string StateId { get; set; }
    
        public virtual State State { get; set; }
        public virtual ICollection<TaxOffice> TaxOffices { get; set; }
        public virtual ICollection<CTINRequest> CTINRequests { get; set; }
        public virtual ICollection<ITINRequest> ITINRequests { get; set; }
    }
}
