//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TAAPs.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class NINData
    {
        public string NATIONAL_IDENTIFICATION_NUMBER { get; set; }
        public string TITLE { get; set; }
        public string SURNAME { get; set; }
        public string FIRST_NAME { get; set; }
        public string MIDDLE_NAME { get; set; }
        public string MAIDEN_NAME { get; set; }
        public string PREVIOUS_SURNAME { get; set; }
        public string PREVIOUS_FIRST_NAME { get; set; }
        public string PREVIOUS_MIDDLE_NAME { get; set; }
        public string OTHER_NAMES { get; set; }
        public System.DateTime BIRTH_DATE { get; set; }
        public string NATIONALITY { get; set; }
        public string BIRTH_COUNTRY { get; set; }
        public string BIRTH_STATE { get; set; }
        public string BIRTH_LGA { get; set; }
        public string GENDER { get; set; }
        public string MARITAL_STATUS { get; set; }
        public string SPOUSE_NIN { get; set; }
        public Nullable<double> HEIGHT { get; set; }
        public string RESIDENCE_STATUS { get; set; }
        public string RELIGION { get; set; }
        public string EMAIL_ADDRESS { get; set; }
        public string TELEPHONE_NO { get; set; }
        public string NATIVE_SPOKEN_LANGUAGE { get; set; }
        public string OTHER_SPOKEN_LANGUAGE { get; set; }
        public string READ_WRITE_LANGUAGE { get; set; }
        public string EDUCATION_LEVEL { get; set; }
        public string PROFESSION { get; set; }
        public string EMPLOYMENT_STATUS { get; set; }
        public string ADDRESS_LINE_ONE { get; set; }
        public string ADDRESS_LINE_TWO { get; set; }
        public string Residence_LGA { get; set; }
        public string Residence_STATE { get; set; }
        public string POST_CODE { get; set; }
        public string TOWN { get; set; }
        public string NOK_ADDRESS_LINE_ONE { get; set; }
        public string NOK_ADDRESS_LINE_TWO { get; set; }
        public string NOK_FIRST_NAME { get; set; }
        public string NOK_SURNAME { get; set; }
        public string NOK_MIDDLE_NAME { get; set; }
        public string NOK_LGA { get; set; }
        public string NOK_STATE { get; set; }
        public string NOK_TOWN { get; set; }
        public string NOK_POST_CODE { get; set; }
        public string NOKNIN { get; set; }
        public string RELATION { get; set; }
        public string ORIGIN_PLACE { get; set; }
        public string ORIGIN_COUNTRY { get; set; }
        public string ORIGIN_STATE { get; set; }
        public string ORIGIN_LGA { get; set; }
        public string GUARDIAN_FIRST_NAME { get; set; }
        public string GUARDIAN_SURNAME { get; set; }
        public string GUARDIAN_MIDDLE_NAME { get; set; }
        public string GUARDIAN_IDENTIFICATION_NUMBER { get; set; }
    }
}
