//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TAAPs.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment
    {
        public string PaymentReference { get; set; }
        public System.DateTime PaymentDate { get; set; }
        public string TIN { get; set; }
        public string TaxpayerName { get; set; }
        public Nullable<int> AssessmentId { get; set; }
        public decimal Amount { get; set; }
        public string PaymentMethod { get; set; }
        public string PaymentDescription { get; set; }
        public string TaxOffice { get; set; }
        public string TaxType { get; set; }
        public string BankBranch { get; set; }
        public string PaymentServiceProvider { get; set; }
    }
}
