//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TAAPs.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class RegisteredCompany
    {
        public RegisteredCompany()
        {
            this.CTINRequests = new HashSet<CTINRequest>();
            this.CTaxpayers = new HashSet<CTaxpayer>();
        }
    
        public string CacNumber { get; set; }
        public string CompanyName { get; set; }
        public System.DateTime RegistrationDate { get; set; }
    
        public virtual ICollection<CTINRequest> CTINRequests { get; set; }
        public virtual ICollection<CTaxpayer> CTaxpayers { get; set; }
    }
}
