//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TAAPs.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Report
    {
        public int ReportId { get; set; }
        public string ReportDesc { get; set; }
        public string ReportName { get; set; }
        public int ReportCategoryId { get; set; }
        public string Url { get; set; }
        public System.DateTime CreateDate { get; set; }
    
        public virtual ReportCategory ReportCategory { get; set; }
    }
}
