//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TAAPs.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class RevenueCollectorReceipt
    {
        public RevenueCollectorReceipt()
        {
            this.ReceiptPrintHistories = new HashSet<ReceiptPrintHistory>();
            this.WHTCreditNotes = new HashSet<WHTCreditNote>();
        }
    
        public string ReceiptId { get; set; }
        public string Reference { get; set; }
        public string ReceivedFrom { get; set; }
        public string Address { get; set; }
        public string TIN { get; set; }
        public string TaxType { get; set; }
        public Nullable<System.DateTime> PaymentDate { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string PeriodCoveredFrom { get; set; }
        public string PeriodCoveredTo { get; set; }
        public string Bank { get; set; }
        public string BankBranch { get; set; }
        public string TaxOffice { get; set; }
        public string PrintStatus { get; set; }
    
        public virtual ICollection<ReceiptPrintHistory> ReceiptPrintHistories { get; set; }
        public virtual ICollection<WHTCreditNote> WHTCreditNotes { get; set; }
    }
}
