//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TAAPs.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class RevenueTarget
    {
        public string TaxOfficeId { get; set; }
        public int Year { get; set; }
        public decimal Target { get; set; }
    
        public virtual TaxOffice TaxOffice { get; set; }
    }
}
