//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TAAPs.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Role
    {
        public Role()
        {
            this.ParentRoleChildren = new HashSet<Role>();
            this.Users = new HashSet<User>();
            this.RoleResources = new HashSet<RoleResource>();
        }
    
        public int RoleId { get; set; }
        public string RoleName { get; set; }
        public Nullable<int> ParentId { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreateDate { get; set; }
    
        public virtual ICollection<Role> ParentRoleChildren { get; set; }
        public virtual Role ParentRole { get; set; }
        public virtual ICollection<User> Users { get; set; }
        public virtual ICollection<RoleResource> RoleResources { get; set; }
    }
}
