//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TAAPs.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class State
    {
        public State()
        {
            this.LGAs = new HashSet<LGA>();
            this.CTINRequests = new HashSet<CTINRequest>();
            this.ITINRequests = new HashSet<ITINRequest>();
        }
    
        public string StateId { get; set; }
        public string StateName { get; set; }
    
        public virtual ICollection<LGA> LGAs { get; set; }
        public virtual ICollection<CTINRequest> CTINRequests { get; set; }
        public virtual ICollection<ITINRequest> ITINRequests { get; set; }
    }
}
