//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TAAPs.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaxExclusion
    {
        public TaxExclusion()
        {
            this.IAssessmentExclusions = new HashSet<IAssessmentExclusion>();
        }
    
        public int ExclusionId { get; set; }
        public string ExclusionName { get; set; }
        public string TaxTypeId { get; set; }
        public bool IsComputed { get; set; }
        public string TaxFunction { get; set; }
    
        public virtual ICollection<IAssessmentExclusion> IAssessmentExclusions { get; set; }
    }
}
