//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TAAPs.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaxOffice
    {
        public TaxOffice()
        {
            this.ITaxpayerTransfers = new HashSet<ITaxpayerTransfer>();
            this.ITaxpayerTransfers1 = new HashSet<ITaxpayerTransfer>();
            this.RevenueTargets = new HashSet<RevenueTarget>();
            this.UserTransfers = new HashSet<UserTransfer>();
            this.UserTransfers1 = new HashSet<UserTransfer>();
            this.CTransfers = new HashSet<CorporateTransfer>();
            this.CTransfers1 = new HashSet<CorporateTransfer>();
            this.Users = new HashSet<User>();
            this.ITaxpayers = new HashSet<ITaxpayer>();
            this.CTaxpayerBranches = new HashSet<CTaxpayerBranch>();
            this.ITINRequests = new HashSet<ITINRequest>();
            this.CTINRequests = new HashSet<CTINRequest>();
            this.CTaxpayers = new HashSet<CTaxpayer>();
        }
    
        public string TaxOfficeId { get; set; }
        public string TaxOfficeName { get; set; }
        public string TaxOfficeTypeId { get; set; }
        public string RegionId { get; set; }
        public string Street { get; set; }
        public string City { get; set; }
        public Nullable<int> LGAId { get; set; }
        public string Telephone { get; set; }
        public string TaxOfficerName { get; set; }
        public string TaxOfficerPhone { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string CreatedBy { get; set; }
    
        public virtual ICollection<ITaxpayerTransfer> ITaxpayerTransfers { get; set; }
        public virtual ICollection<ITaxpayerTransfer> ITaxpayerTransfers1 { get; set; }
        public virtual LGA LGA { get; set; }
        public virtual ICollection<RevenueTarget> RevenueTargets { get; set; }
        public virtual TaxOfficeRegion TaxOfficeRegion { get; set; }
        public virtual ICollection<UserTransfer> UserTransfers { get; set; }
        public virtual ICollection<UserTransfer> UserTransfers1 { get; set; }
        public virtual ICollection<CorporateTransfer> CTransfers { get; set; }
        public virtual ICollection<CorporateTransfer> CTransfers1 { get; set; }
        public virtual ICollection<User> Users { get; set; }
        public virtual TaxOfficeType TaxOfficeType { get; set; }
        public virtual ICollection<ITaxpayer> ITaxpayers { get; set; }
        public virtual ICollection<CTaxpayerBranch> CTaxpayerBranches { get; set; }
        public virtual ICollection<ITINRequest> ITINRequests { get; set; }
        public virtual ICollection<CTINRequest> CTINRequests { get; set; }
        public virtual ICollection<CTaxpayer> CTaxpayers { get; set; }
    }
}
