//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TAAPs.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserTransfer
    {
        public int TransferId { get; set; }
        public string UserName { get; set; }
        public string FromTaxOfficeId { get; set; }
        public string ToTaxOfficeId { get; set; }
        public string Reason { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreateDate { get; set; }
    
        public virtual User User { get; set; }
        public virtual TaxOffice TaxOffice { get; set; }
        public virtual TaxOffice TaxOffice1 { get; set; }
    }
}
