//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TAAPs.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.CTransfers = new HashSet<CorporateTransfer>();
            this.ReceiptPrintHistory = new HashSet<ReceiptPrintHistory>();
            this.Users1 = new HashSet<User>();
            this.UserTransfers = new HashSet<UserTransfer>();
            this.CBanks = new HashSet<CBank>();
            this.CTurnovers = new HashSet<CTurnover>();
            this.GeneratedReceipts = new HashSet<GeneratedReceipt>();
            this.IAssessments = new HashSet<IAssessment>();
            this.TaxTypes = new HashSet<TaxType>();
            this.IAssessmentFiles = new HashSet<IAssessmentFile>();
            this.UserLoginHistories = new HashSet<UserLoginHistory>();
            this.CTaxpayerFiles = new HashSet<CTaxpayerFile>();
            this.IPenalties = new HashSet<IPenalty>();
            this.ITaxpayerAddresses = new HashSet<ITaxpayerAddress>();
            this.ITaxpayerNoKs = new HashSet<ITaxpayerNoK>();
            this.ITaxpayers = new HashSet<ITaxpayer>();
            this.ITaxpayerFiles = new HashSet<ITaxpayerFile>();
            this.IssueLogs = new HashSet<IssueLog>();
            this.CTaxpayers = new HashSet<CTaxpayer>();
            this.CTINRequests = new HashSet<CTINRequest>();
        }
    
        public string UserName { get; set; }
        public string PasswordHash { get; set; }
        public string Salt { get; set; }
        public string LastName { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string Title { get; set; }
        public int RoleId { get; set; }
        public string TaxOfficeId { get; set; }
        public string Email { get; set; }
        public bool ChangePassword { get; set; }
        public string StaffId { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string CreatedBy { get; set; }
        public string RegionId { get; set; }
    
        public virtual ICollection<CorporateTransfer> CTransfers { get; set; }
        public virtual ICollection<ReceiptPrintHistory> ReceiptPrintHistory { get; set; }
        public virtual Role Role { get; set; }
        public virtual ICollection<User> Users1 { get; set; }
        public virtual User User1 { get; set; }
        public virtual ICollection<UserTransfer> UserTransfers { get; set; }
        public virtual ICollection<CBank> CBanks { get; set; }
        public virtual ICollection<CTurnover> CTurnovers { get; set; }
        public virtual TaxOfficeRegion TaxOfficeRegion { get; set; }
        public virtual ICollection<GeneratedReceipt> GeneratedReceipts { get; set; }
        public virtual ICollection<IAssessment> IAssessments { get; set; }
        public virtual ICollection<TaxType> TaxTypes { get; set; }
        public virtual ICollection<IAssessmentFile> IAssessmentFiles { get; set; }
        public virtual ICollection<UserLoginHistory> UserLoginHistories { get; set; }
        public virtual ICollection<CTaxpayerFile> CTaxpayerFiles { get; set; }
        public virtual ICollection<IPenalty> IPenalties { get; set; }
        public virtual ICollection<ITaxpayerAddress> ITaxpayerAddresses { get; set; }
        public virtual ICollection<ITaxpayerNoK> ITaxpayerNoKs { get; set; }
        public virtual ICollection<ITaxpayer> ITaxpayers { get; set; }
        public virtual ICollection<ITaxpayerFile> ITaxpayerFiles { get; set; }
        public virtual ICollection<IssueLog> IssueLogs { get; set; }
        public virtual ICollection<CTaxpayer> CTaxpayers { get; set; }
        public virtual ICollection<CTINRequest> CTINRequests { get; set; }
        public virtual TaxOffice TaxOffice { get; set; }
    }
}
